### PR TITLE
Web UI to manage board election

### PR DESCRIPTION
**Pull request by ndeloof**
Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>

require some extra configuration parameters: 

- [ ] electionCandidates : coma separated list of candidates
- [ ] electionLogfile : path to store collected votes. assume this path is well persisted/backup
- [ ] electionOpen : date app will start collecting votes. yyyy/MM/dd 
- [ ] electionClose : date election will close. yyyy/MM/dd

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by rtyler** [comment]
@ndeloof can you update the README or provide additional documentation for how to set up the board candidates, what files go where, etc? That way I will be able to deploy this successfully once the code is wrapped up

**Comment by rtyler** [comment]
bump

halp

**Comment by ndeloof** [comment]
@rtyler see PR description for configuration parameters

**Comment by olblak** [comment]
@rtyler What's missing for this PR to be merged? 
@ndeloof I added a docker entrypoint  to configure accountapp docker image through environment variables. it doesn't configure this PR yet but I can submit a patch if you merge master changes

**Comment by rtyler** [comment]
@olblak The biggest thing that should be done is some manual testing of these changes. Since this repo doesn't really have any tests whatsoever, a manual verification should be done before these are merged. 

You're more than welcome to take that task on for me :smile:

**Pull request merged**
