### PR TITLE
Add spacing to forms, remove tether

### LINKED ISSUE #197: Spacing broken after upgrade to bootstrap 5 on jenkins.io
Caused by https://github.com/jenkins-infra/jenkins.io/pull/5436

cc @zbynek 

image

on many pages buttons are now touching inputs

see https://github.com/jenkins-infra/account-app/pull/146 for example screenshots of what it should look like

### PR DESCRIPTION
**Pull request by zbynek**
Fixes #197 

Also Tether is no longer needed since components are used for popups. If any other popups outside of header get implemented in the future, Popper should be used instead of Tether.

### CODE REVIEW

**Review by lemeurherve — APPROVED** [review]
Before:
image

After:
image

**Review by timja — COMMENTED** [review]
buttons seem to look overly big (46px vs 38px inputs, at least on login and signup pages) and login and sign up pages are no longer using full width buttons, thoughts?

**Comment by zbynek** [comment]
@timja do you think the version after last commit is better?

**Review by timja — APPROVED** [review]
Thanks, looks better now!

**Pull request merged**
