### PR TITLE
Switch to using web component version of nav bar

### PR DESCRIPTION
**Pull request by halkeye**
What it looks like right now

image

What it looks like with web component:

image

I realized there's a need to allow sites to extend the nav bar, so i'll add support for it, but I still think its a possible win.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
FWIW I tested this locally in Chrome and there's a bit of delay waiting for the header to load, e.g. the page loads without the header and then it appears, probably should be render blocking?

**Comment by halkeye** [comment]
I'm not really sure how to make it block, I think it's the nature of web components. It caches really well though

**Comment by timja** [comment]
Could possibly bundle it in the app?

**Comment by halkeye** [comment]
Unpkg is a pretty fast cdn and has better support for ESM modules.

If you refresh again it's it slow?

**Comment by halkeye** [comment]
Oh wait I see what you mean. The first paint is slow. I can move the script tags to the end and async them

**Comment by timja** [comment]
Sure if that helps, created https://github.com/jenkins-infra/account-app/issues/147 for tracking

**Pull request merged**
