### PR TITLE
Try and accelerate the spammer triage process

### PR DESCRIPTION
**Pull request by batmat**
Reformatted a bit to make it more readable + added requirement to
explain why people need an account, so that it's easier and quicker for
infra team to decide it's likely a real user or an effin' spammer.

### CODE REVIEW

**Comment by batmat** [comment]
As requested @larrys :-) here's already a proposal

**Comment by larrys** [comment]
This conflicts with https://github.com/jenkins-infra/account-app/pull/31 (which has some other changes in it)

**Comment by batmat** [comment]
No problem, I'll rebase onto it when merged. Btw, that makes another argument in favor of splitting the test in many lines: that it would make history, conflict resolution and diff doable per (sub)sentence.

**Comment by larrys** [comment]
My main change was to remove the link to the google groups, which you could easily incorporate. Or maybe we could link to a wiki page instead, so it does not require code changes to change our message when this gets triggered.

**Comment by batmat** [comment]
OK, got it for your first sentence, just force pushed with #31 text change.

For the wiki page, you mean linking to some page like 'Requesting an account under special conditions' or something like that?

Replacing the whole text w/ just :  
```
Due to the spam problem, we need additional verification for your sign-up request.
Please refer to <a href="TODO">the associated documentation to get your account created</a>.
```

WDYT?

**Comment by larrys** [comment]
Including @rtyler @kohsuke @daniel-beck @abayer  to provide feedback.

I think referring them to the wiki where we have the information is a good start, so we don't require code changes to change the verbiage.

However, it might be helpful to instead have that page (that rejects account creation) with a form for them to fill out asking them for further information to help us determine if they will spam or not. Then the content of that form (plus other information we collected along the way) is included in the email that normally is emailed to a mailing list (not the dev list, the current list should be fine, provided we stop getting mails hit by a spam filter)

Then the user does not have to send an email at all. We just need volunteers to monitor this mailing list, and act on real humans. We could still link them to a wiki page so if they wanted to follow up on their request, then they can ping the dev list. (I've tried to avoid having it create something like a JIRA ticket, since that would complicate things even more).

**Comment by batmat** [comment]
:+1: and to make it easier for admins, there could even be a unique generated link in the email (is there already? I didn't check the code) to directly validate a request that clearly seems legit (?)

**Comment by larrys** [comment]
It provides a link to create the account, but that is a GET request with all the values pre-filled out.

The current problem is that the subject is the same, so Gmail buckets them all together, so I think the subject should be a bit more unique (my pull request referenced above addresses this by including their first and last name in the email subject)

**Comment by batmat** [comment]
Rebased onto just merged #31 just in case.

**Pull request merged**
